services:
  app:
    build: .
    container_name: caisse-app
    environment:
      PYTHONPATH: /app/src
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh db:3306 -t 60 -- && /app/entrypoint.sh

  db:
    image: mysql:8.3
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
