global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'django-containers'
    metrics_path: /metrics

    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"

    relabel_configs:
      # Ne garder que les conteneurs du service 'app'
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: app
        action: keep

      # Forcer le port de scrape à 5000 (Django)
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        replacement: '$1:5000'
        target_label: __address__

      # Taguer chaque métrique avec le nom du conteneur
      - source_labels: [__meta_docker_container_name]
        target_label: instance
