@startuml

title Diagramme de classes - Application de caisse

' Définir les classes
class Magasin {
    +nom: CharField
    +quartier: CharField
    +type: CharField
}

class Produit {
    +nom: CharField
    +prix: FloatField
    +description: TextField
}

class Stock {
    +quantite: IntegerField
}

class Vente {
    +date_heure: DateTimeField
    +total: FloatField
}

class VenteProduit {
    +quantite: IntegerField
    +prix_unitaire: FloatField
}

' Définir les relations entre les classes
Magasin "1" -- "many" Stock : possède >
Produit "1" -- "many" Stock : stocké dans >
Magasin "1" -- "many" Vente : réalise >
Vente "1" -- "many" VenteProduit : contient >
Produit "1" -- "many" VenteProduit : vendu dans >

@enduml
