@startuml
node "Client" as Client {
  [Navigateur Web]
}

node "Serveur Applicatif" as AppServer {
  artifact "Docker Container\n- Django (manage.py runserver)\n- Application caisse" as DjangoApp
}

node "Serveur Base de Données" as DBServer {
  artifact "Docker Container\n- MySQL" as MySQLDB
}

Client --> DjangoApp : HTTP/HTTPS
DjangoApp --> MySQLDB : Connexion MySQL (port 3306)

folder "Volume Docker" as Volume
MySQLDB ..> Volume : Persistance données

@enduml
